service: user-management-service

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9

functions:
  icompaas-API:
    name: icompaas-API   # for custom lambda function name
    handler: wsgi_handler.handler
    layers:
      - arn:aws:lambda:us-east-1:216320741878:layer:pymysql:2 
    events:
      - httpApi:
          path: /users
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
